version: '3.7'
services:
  client:
    image: oa2client:latest
    ports:
       - "3000:3000"
    restart: always
    container_name: oa2client
    environment:
      - DENO_AUTHORIZE_URL=${DENO_AUTHORIZE_URL}
      - DENO_TOKEN_URL=${DENO_TOKEN_URL}
      - DENO_CLIENT_ID=${DENO_CLIENT_ID}
      - DENO_CLIENT_SECRET=${DENO_CLIENT_SECRET}
      - DENO_CLIENT_REDIRECT_URL=${DENO_CLIENT_REDIRECT_URL}
  server:
    image: oa2server:latest
    ports:
       - "9001:9001"
    restart: always
    container_name: oa2server
    volumes:
      - "${PWD}/:/app"    
    environment:
      - DENO_CLIENT_ID=${DENO_CLIENT_ID}
      - DENO_CLIENT_SECRET=${DENO_CLIENT_SECRET}
      - DENO_CLIENT_REDIRECT_URL=${DENO_CLIENT_REDIRECT_URL}
      - DENO_FILE_TOKENS_DB=${DENO_FILE_TOKENS_DB}
  resource:
    image: oa2resource:latest
    ports:
       - "7000:7000"
    restart: always
    container_name: oa2resource
    volumes:
      - "${PWD}/:/app"
    environment:
      - DENO_INTROSPECT_URL=${DENO_AUTHORIZE_URL}
