FROM denoland/deno:1.14.3

WORKDIR /app

# Cache the dependencies as a layer
COPY deps.ts mod.ts ./
RUN deno cache deps.ts

# These steps will be re-run upon each file change in your working directory
COPY src src
COPY examples examples

RUN deno cache ./examples/oauth2_resource.ts && touch tokens.db

EXPOSE 7000
USER deno

CMD ["run", "--allow-net","--allow-read", "--allow-write","--allow-env", "./examples/oauth2_resource.ts"]

# docker run --rm --mount type=bind,source="$(pwd)"/,target=/app/ -p 7000:7000 -it oa2resource